# Generated by Django 4.2 on 2023-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='clients_title',
            field=models.CharField(max_length=40),
        ),
    ]
