# Generated by Django 4.2 on 2023-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_websitesetting_clients_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='cta_title',
            field=models.CharField(max_length=50),
        ),
    ]
