# Generated by Django 4.2 on 2023-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_websitesetting_clients_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='designer_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='designer_profile',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='designs_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
