# Generated by Django 4.2 on 2023-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
