# Generated by Django 4.2 on 2023-10-05 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_articlecategory_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
