# Generated by Django 4.2 on 2023-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_article_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='contact_page_content_title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='contact_page_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='contact_page_pre_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='contact_page_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
