# Generated by Django 4.2 on 2023-10-07 18:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_websitesetting_email_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_content_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_content_title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_main_content_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_main_content_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_together_work_desc',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_together_work_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_page_value_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='more_abouts_owner_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='more_abouts_owner_title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
