# Generated by Django 4.2 on 2023-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_websitesetting_about_page_content_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
            ],
        ),
    ]
