# Generated by Django 4.2 on 2023-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_servicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='blog_page_pre_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='blog_page_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
