# Generated by Django 4.2 on 2023-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_websitesetting_blog_page_pre_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blockquote_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='blockquote_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
