# Generated by Django 4.2 on 2023-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_article_blockquote_desc_article_blockquote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blockquote_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='blockquote_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
