# Generated by Django 4.2 on 2024-12-10 20:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_article_blockquote_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc2',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='desc3',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
